[build]
 command = "npm run build"
 functions = "functions"
 publish = "public"

[[redirects]]
 to="/.netlify/functions/stripe-api/:splat"
 from = "/*"
 status = 200

 [[redirects]]
  from = "/*"
  to = "index.html"
  status = 200